### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by Arnav7501** [jonestristand/react-native-metronome-module#3] opened 2022-09-01 03:10 UTC
hi, when i try to run, it says

TypeError: null is not an object (evaluating '_reactNativeMetronomeModule.default.setBPM')

**Comment by jonestristand** [comment] 2022-09-01 03:12
Hey!

Thanks for the report! I'll need a bit more detail to track down the issue. Can you provide me with some details of your environment (OS, node version, Android or iOS), and steps to reproduce? Thanks!!

**Comment by Arnav7501** [comment] 2022-09-01 03:47
Hi,
thanks a lot for the quick response
I'm running this on expo, and I'm sorry if this is a stupid question as I'm new to react native
node version: v16.15.1
running on vscode
I installed the metronome through the terminal, then
I tried making a very simple outline just to see if i could get the metronome to work:

import MetronomeModule from "react-native-metronome-module";


const App = () =>  {
MetronomeModule.setBPM(100);
MetronomeModule.setShouldPauseOnLostFocus(true);
MetronomeModule.start();

}
export default App;

on running i get the error.

**Comment by jonestristand** [comment] 2022-09-01 04:09
Are you running it in ios or android emulator? Also what OS are you using?

**Comment by Arnav7501** [comment] 2022-09-01 04:14
I'm running in an IOS emulator, OS is Mac

**Comment by jonestristand** [comment] 2022-09-01 04:16
have you run pod install?

**Comment by Arnav7501** [comment] 2022-09-01 04:21
Pods is incompatible with Expo, when i searched online it said i didn't need it because expo handles it

**Comment by jonestristand** [comment] 2022-09-05 06:07
I will look into this

**Comment by iankleist** [comment] 2022-10-16 19:19
Ran into the same error. Have you tried it with Expo?

**Comment by jonestristand** [comment] 2022-10-17 21:25
I haven't had a chance to yet, my project is ongoing and doesn't use Expo, so I have no experience with it...

**Comment by iankleist** [comment] 2022-11-24 11:48
Hi, I ejected my app and now I get the following error:

`
❌  (node_modules/react-native-metronome-module/ios/MetronomeModule.swift:44:55)

  42 |
  43 |     do {
> 44 |       try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault);
     |                                                       ^ 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
  45 |       try AVAudioSession.sharedInstance().setActive(true);
  46 |
  47 |       self.player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.wav.rawValue);


❌  (node_modules/react-native-metronome-module/ios/MetronomeModule.swift:44:93)

  42 |
  43 |     do {
> 44 |       try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault);
     |                                                                                             ^ 'AVAudioSessionModeDefault' has been renamed to 'AVAudioSession.Mode.default'
  45 |       try AVAudioSession.sharedInstance().setActive(true);
  46 |
  47 |       self.player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.wav.rawValue);
`

**Comment by rinkalsoc** [comment] 2022-12-14 05:35
> hi, when i try to run, it says
> 
> TypeError: null is not an object (evaluating '_reactNativeMetronomeModule.default.setBPM')

Hi any one getting solution for this ?

**Comment by jonestristand** [comment] 2022-12-14 07:40
Hey guys, sorry I haven't had time to look at this yet but will happily take a PR if anyone sorts it out in the meantime. When I'm able to get to it I will post a note here.

**Comment by ironicbrew** [comment] 2022-12-30 16:12
> Hey guys, sorry I haven't had time to look at this yet but will happily take a PR if anyone sorts it out in the meantime. When I'm able to get to it I will post a note here.

@jonestristand PR created which will fix the ```'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'``` error. Although I'm not getting any audio playback as per #4 so interested to see if anyone else can get it working on their end.

Original issue ```TypeError: null is not an object (evaluating '_reactNativeMetronomeModule.default.setBPM')``` is caused by trying to use native modules in expo and is solved by ejecting and ensuring pods are installed with ```npx pod-install```. I don't think there's a way to use native module like this in the expo environment.

**Comment by jonestristand** [comment] 2022-12-30 22:16
Merged, thanks for the PR!

**Closed as completed** 2022-12-30 22:16 UTC
